library("dplyr")
install.packages("dplyr")
library(dplyr)
getwd()
moosedata <- read.csv("MoosePopulation.csv")
View(moosedata)
moose_clean <- na.omit(moosedata)
View(moose_clean)
moose_sel <- select(moose_clean, Ecoregion, Year, Area, Estimated_Moose_Pop)
View(moose_sel)
year_min <- min(moose_sel$year)
year_min <- min(moose_selYear)
library(dplyr)
moose_sel <- select(moose_clean, Ecoregion, Year, Area, Estimated_Moose_Pop)
year_min <- min(moose-sel, Year)
year_min <- min(moose_sel, Year)
year_min <- min(moose_sel$Year, na.rm = TRUE)
year_min
moose_max <- max(moose_sel$Estimated_Moose_Pop
moose_max
moose_max <- max(moose_sel$Estimated_Moose_Pop
, na.rm = TRUE
\
moose_max <- max(moose_sel$Estimated_Moose_Pop,na.rm = TRUE)
moose_max
moosedata2 <- mutate(moose_sel, MooseDensity = Estimated_Moose_Pop/Area)
plot(moosedata2$Year, moosedata2$MooseDensity, xlab = "year", ylab = "Moose per sq km", main = "Moose density in Newfoundland ecoregions over time")
moose_west <- filter(moosedata2, Ecoregion == "Western_Forests")
plot(estern$Year, western$density, typer = "1", xlab = "Year", ylab = "Moose Density (Moose per km^2)", main = "Change in Moose Density Over Time in Western Forests")
plot(western$Year, western$density, type = "1", xlab = "Year", ylab = "Moose Density (Moose Per km^2)", main = "Change in Moose Density Over Time in Western Forests")
plot(moose_west$Year, moose_west$density, type = "1", xlab = "year", ylab = "Moose Density (Moose per km^2)", main = "Change in Moose Density Over Time in Western Forests")
plot(moose_west$Year, moose_west$density, xlab = "year", ylab = "Moose Density (Moose per km^2)", main = "Change in Moose Density Over Time in Western Forests")
moose_2020 <- filter(moosedata2, Ecoregion == "Western_Forests")
moose_2020_high <- filter(moose_2020, density > 2.0)
moose_2020_high <- filter(moose_2020, MooseDensity <2.0)
moose_2020_high <- filter(moose_2020, MooseDensity <2.0)
moose_2020_high_byD <- arrange(Dataset, desc(ColumnName))
moose_2020_high_byD <- arrange(moose_2020_high, desc(ColumnName))
View(moose_2020_high)
moose_2020_high_byD <- arrange(moose_2020_high, desc(MooseDensity))
moosefinal <- moosedata2 %>% filter(Year == 2020) %>% filter(MooseDensity > 2.0) %>% arrange(desc(MooseDensity)) %>% print()
library(readr)
SaplingStudy <- read_csv("SaplingStudy.csv")
View(SaplingStudy)
saplings <- read.csv(SaplingStudy)
sap_clean <- na.omit(SaplingStudy)
sap_reg_browse <- group_by(Ecoregion) %>% summarize(mean(BrowsingScore)) %>% print()
sap_reg_browse <- group_by(Ecoregion) %>% summarize(sap_clean) %>% mean(BrowsingScore) %>% print()
sap_reg_browse <- sap_clean %>% group_by(Ecoregion) %>% summarize(AverageBrowsing = mean(BrowsingScore, na.rm = TRUE))
print(sap_reg_browse)
View(sap_reg_browse)
avg_browse_reg <- sap_reg_browse %>% arrange(desc(AverageBrowsing))
Print(avg_browse_reg)
print(avg_browse_reg)
#Northern_Peninsula_Forests has the highest, while StraitOfBelleIsleBarrens has the lowest average browsing scores
View(moosefinal)
View(sap_clean)
library(dplyr)
sap_reg_height <- SaplingStudy %>% group_by(Ecoregion) %>% summarize(mean_height = mean(Height, na.rm = TRUE))
print(sap_reg_height)
sap_reg_height_low <- sap_reg_height %>% filter(mean_height < 20)
print(sap_reg_height_low)
#These ecoregions have average sapling heights less than 20 cm, suggesting they may be severly browsed by moose.
sap_spe_browse <- SaplingStudy %>% group_by(Species) %>% summarize(mean_browse = mena(BrowsingScore, na.rm = TRUE))
sap_spe_browse <- SaplingStudy %>% group_by(Species) %>% summarize(mean_browse = mean(BrowsingScore, na.rm = TRUE))
print(sap_spe_browse)
avg_browse_spe <- sap_spe_browse %>% arrange(desc(mean_browse))
print(avg_browse_spe)
#The species at the top has the higest average browsing score, the species att he bottom has the lowest average browsing score.
fir_reg_browse <- SaplingStudy %>% filter(Species == "Balsam_Fir") %>% group_by(Ecoregion) %>% summarize(mean_browse = mean(BrowsingScore, na.rm = True))
fir_reg_browse <- SpalingStudy %>% filter(Species == "Balman_fir") %>% group_by(Ecoregion) %>% summarize(mean_browse = mean(BrowingScore, na.rm = TRUE))
fir_reg_browse <- SaplingStudy %>% filter(Secies == "Balsam_fir") %>% group_by(Ecoregion) %>% summarize(mean_browse = mean(BrowsingScore, na.rm = TRUE))
fir_reg_browse <- SaplingStudy %>% filter(Species == "Balsam_Fir") %>% group_by(Ecoregion) %>% summarize(mean_browse = mean(BrowsingScore, na.rm = TRUE))
print(fir_reg_browse)
barplot(fir_reg_browse$mean_browse, names.arg = fir_reg_browse$Ecoregion, xlab = "Ecoregion", ylab = "Average Browsing Score", main = "Average Balsam Fir Browsing by Ecoregion", col = "forestgreen", cex.names = 0.6)
spruce_reg_browse <- SaplingStudy %>% filter(Species == "Black_Spruce") %>% group_by(Ecoregion) %>% summarize(mean_BrowsingScore = mean(BrowsingScore, na.rm = TRUE))
print(spruce_reg_browse)
barplot(height = spruce_reg_browse$mean_BrowsingScore, names.arg = spruce_reg_browse$Ecoregion, las = 2, ylab = "Average Browsing Score", xlab = "Ecoregion", main = "Average Moose Browsing on Black Spruce by Ecoregion")
#Black spruce generally shows a lower average browsing score compared to balsam fir. This suggests moose prefer browsing balsam fir more than black spruce.
sap_reg_tally <- sap_clean %>% group_by(Ecoregion) %>% tally()
print(sap_reg_tally)
sap_spe_tally <- sap_clean %>% group_by(Species) %>% tally()
print(sap_spe_tally)
#The SaplingStudy dataset does not apprear to be evenly distributed. Some Ecoregions and/or tree specied have higher sample counts than others, meaning some are overrepresented while others are underrepresented.
#It is important to recognize bias in ecological datasets because uneven sampling can distort patterns and lead to incorrect conclusions. If certain species or regions are oversampled, the results may not be accurate.
moose_2020b <- moose_clean %>% filter(Year == 2020) %>% mutate(MooseDensity = MooseCount / Area)
moose_2020b <- moose_clean %>% filter(Year == 2020) %>% mutate(MooseDensity = Estimated_Moose_Pop / Area)
print(moose_2020b)
moose_sap <- moose_2020b %>% left_join(sap_clean, by = "Ecoregion")
head(moose_sap)
sum_spe_browse <- moose_sap %>% group_by(Species, Ecoregion) %>% summarize(mean_BrowsingScore = mean(BrowsingScore, na.rm = TRUE), mean_MooseDensity = mean(MooseDensity, na.rm = TRUE))
print(sum_spe_browse)
library(dplyr)
#Moose prefer certain species at low density, but browse more species at higher density.
#Moose favour willow the most and browse black spruce the least.
#The missing species was likely excluded due to little browsing or not enough data.
collisions2020 <- c(56, 60, 14, 36, 48, 10, 40, 110, 6)
human_pop <- c(18000, 12000, 4000, 75100, 24000, 3500, 32000, 270000, 2300)
study_sites <- c("North_Shore_Forests", "Northern_Peninsula_Forests", "Long_Range_Barrens", "Central_Forests", "Western_Forests", "EasternHyperOceanicBarrens", "Maritime_Barrens", "Avalon_Forests", "StraitOfBalleIsleBarrens")
moose_coll <- data.frame(collisions2020, human_pop, study_sites)
moose_coll2 <- moose_coll %>% rename("Ecoregion", .cols = study_sites)
moose_coll2 <- moose_coll %>% rename_with("Ecoregion", .cols = study_sites)
moose_coll2 <- moose_coll %>% rename_with(~"Ecoregion", .cols = study_sites)
coll_merge <- left_join(moose_coll2, moose_2020, by = "Ecoregion")
print(coll_merge)
plota(coll_merge$MooseDensity, coll_merge$collisions2020, xlab = "Moose Density", ylab = "Moose-Vehicle Collisions (2020)", main = "Moose Density vs. Collisions (2020)")
plot(coll_merge$MooseDensity, coll_merge$collisions2020, xlab = "Moose Density", ylab = "Moose-Vehicle collisions (2020)", main = "Moose Density vs. Collisions (2020)")
#There is a positive relationship, higher moose density gernerally means more collisions. One point may be a possible outlier.
coll_merge_per_capita <- coll_merge %>% mutate(coll_per_capita = collisions2020 / human_pop)
plot(coll_merge_per_capita$human_pop, coll_merge_per_capita$coll_per_capita, xlab = "Human Population", ylab = "Collisions per Capita", main = "Collisions per Capita vs. Human Population")
#Collisions per capita are higher in areas with smaller populations. This makes sense since rural areas in Newfoundland have more moose and fewer people.
